### ISSUE TITLE
Scroll not working in search results

### ISSUE THREAD

**Issue by akashbhumiwal** [Chandrasekar-G/react-native-searchable-list#4]
If u add multiple elements in your array the list size increased but its not scrolling in Android. It is performing perfectly in iOS

**Comment by nileshrajpoot** [comment]
In react native??

**Comment by nileshrajpoot** [comment]
I will seen code then confirm what is issue

**Comment by akashbhumiwal** [comment]
Hello,
Thanks for the prompt response guys but I have fixed the issue. We need to add certain height in case of android to make it scroll after providing certain height things work perfectly.

Thanks and regards
Aakash bhumiwal
Evon Technologies

**Comment by Chandrasekar-G** [comment]
Thanks, @akashbhumiwal. Closing it since this is not related to the npm package.
